version: "3"
services:
  client_dev:
    build: ./client
    command: sh -c "npm run start"
    ports:
      - 8000:3000
    working_dir: /home/app/client
    volumes:
      - ./client:/home/app/client
  api_dev:
    build: ./server
    command: sh -c "npm install && npm run dev"
    ports:
      - 5000:5000
    working_dir: /home/app/server
    volumes:
      - ./api:/home/app/server
   
  